--- #YAML:1.0
name: Class-CGI
version: 0.14
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: "Fetch objects from your CGI object"
license: perl
generated_by: Module::Build version 0.2704, without YAML.pm
